import time
Name = input("Hi Detective Whats Your Name: ")
print ("Great Detective" , Name)
time.sleep(0.40)
print ("Lets Goo")
time.sleep(1)
print ("Loading.................")
time.sleep(2)
print ("It was a cold, silent night in the city of Orlington.")
time.sleep(3)
print ("At 2:47 a.m., the museum alarm blared through the dark —")
time.sleep(3)
print ("“The Star of Eternity Diamond has been stolen!”")
time.sleep(3)
print ("By morning, the museum was surrounded by flashing police lights and reporters.")
time.sleep(3)
print ("Inside, stood Detective" , Name , "one of the city’s youngest and sharpest minds.")
time.sleep(3)
print ("The glass case was shattered, and the priceless blue diamond was gone.")
time.sleep(3)
print ("There were three suspects — each with a reason, each with a secret.")
time.sleep(3)
print ("1.The Guard, Mr. Roland")
time.sleep(3)
print ("2.The Cleaner, Mr. Felix")
time.sleep(3)
print ("3.The Artist, Ms. Vera ")
Choose = input(f"You Detective {Name} had to decide :\n Who to question first? \n Mr roland (A)\nMr felix (B)\nMs.Vera(C) \n choose: ")
if Choose.lower() == "a" or Choose.lower() == "Mr roland":
    print ("He claimed he was outside all night.\n But his hands were trembling, and his forehead glistened with sweat.")
if Choose.lower() == "b" or Choose.lower() == "Mr felix":
    print ("He claimed he was mopping until midnight.\n His mop was spotless — too spotless.")
if Choose.lower() == "c" or Choose.lower() == "Ms Vera":
    print ("She said I was painting a diamond portrait for the museum’s gallery.\n She smiled too calmly for someone so close to the scene.")
    time.sleep(2)
print ("Scene 2: The Clues")
time.sleep(1)
print ("As you explored the crime scene, three clues caught your eye: ")
time.sleep(2)
print ("1.A broken key near the security door.")
time.sleep(1)
print ("2.Drops of blue paint leading toward the exit.")

print ("3.Footprints ending near the cleaning closet.")
Inspect = input("what to inspect first: \n 1.broken key \n 2.blue paint \n 3.footprints\n Choose by 1,2,3: ")
if Inspect == '1':
    print ("The broken key matched the guard’s locker.")
if Inspect == '2':
    print ("The blue paint looked exactly like the artist’s color.")
if Inspect == '3':
    print ("The footprints were the same size as the cleaner’s boots.")
time.sleep(2)
    
print ("Scene 3: The CCTV")
time.sleep(2)
print ("You checked the CCTV footage, hoping for answers.\nBut the thief’s face was covered. Only one detail stood out:")
time.sleep(2)
print ("A black hat with a silver stripe.")
time.sleep(3)
print ("You recalled something…\nThe guard had a cap — dark blue.")
print ("The cleaner had a plain white one.\nThe artist wore a black hat — exactly like in the footage.")
time.sleep(4)
print ("Scene 4: The Accusation")
time.sleep(2)
print ("You gathered everyone in the main hall.\nAll eyes were on you.")
print ("The museum director asked softly: \n “Detective, have you found our thief?”")
time.sleep(2)
print ("You stepped forward.")
time.sleep(2)
Accuse = input("Who to excuse: artist(A)/cleaner(B)/guard(C): ")
if Accuse.lower() == "artist" or Accuse.lower() == "a":
    print ("“She said Im a Muslim I will not steal\nhours later,\NO EVIDENCE FOUND")
    continue
if Accuse.lower() == "cleaner" or Accuse.lower() == "b":
    print ("he panics and runs — dropping the diamond mid-escape.\nYou chase him down and handcuff him on the museum steps.\nThe crowd cheers your name.")
if Accuse.lower() == "guard" or Accuse.lower() == "c":
    print ("he bursts into tears and confesses.\nHe wanted to sell the diamond to pay off debts.\nThe case is closed — but something still feels too easy.")
time.sleep(5)
print ("THE EPILOUGE")
time.sleep(2)
print ("The Star of Eternity is returned to its display case,\n shining brighter than ever under the museum lights.")
time.sleep(2)
print ("Detective" , Name , "walks away as cameras flash.\nAnother mystery solved.\nAnother night of glory.")
time.sleep(2)
print ("But somewhere in the city, another story begins...")
time.sleep(2)

print ("🔚 The End")

